---
abstract: 'Email::MIME::Kit-based bulk mailer'
author:
  - 'Jesse Luehrs    <doy@cpan.org>'
  - 'Yanick Champoux <yanick.champoux@iinteractive.com>'
build_requires:
  Email::Sender::Transport::Maildir: '0'
  Exporter: '0'
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Path::Tiny: '0'
  Test::More: '0'
  lib: '0'
  parent: '0'
  perl: '5.006'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.043, CPAN::Meta::Converter version 2.150001'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Email-MIME-Kit-Bulk
provides:
  Email::MIME::Kit::Bulk:
    file: lib/Email/MIME/Kit/Bulk.pm
    version: v0.0.3
  Email::MIME::Kit::Bulk::Command:
    file: lib/Email/MIME/Kit/Bulk/Command.pm
    version: v0.0.3
  Email::MIME::Kit::Bulk::Kit:
    file: lib/Email/MIME/Kit/Bulk/Kit.pm
    version: v0.0.3
  Email::MIME::Kit::Bulk::ManifestReader::JSON:
    file: lib/Email/MIME/Kit/Bulk/ManifestReader/JSON.pm
    version: v0.0.3
  Email::MIME::Kit::Bulk::Target:
    file: lib/Email/MIME/Kit/Bulk/Target.pm
    version: v0.0.3
requires:
  Email::MIME: '0'
  Email::MIME::Kit: '3.000005'
  Email::MIME::Kit::ManifestReader::JSON: '0'
  Email::MIME::Kit::Renderer::TT: '0'
  Email::Sender::Simple: '0'
  JSON: '0'
  List::AllUtils: '0'
  MCE::Map: '0'
  Moose: '0'
  MooseX::App::Simple: '0'
  MooseX::Types::Email: '0'
  MooseX::Types::Path::Tiny: '0'
  PerlX::Maybe: '0'
  Try::Tiny: '0'
  namespace::autoclean: '0'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/iinteractive/Email-MIME-Kit-Bulk/issues
  homepage: https://github.com/iinteractive/Email-MIME-Kit-Bulk
  repository: https://github.com/iinteractive/Email-MIME-Kit-Bulk.git
version: 0.0.3
x_authority: cpan:YANICK
x_contributors:
  - 'Jesse Luehrs <jesse.luehrs@iinteractive.com>'
